
export interface ProjectRow {
  id: number;
  srNo: string;
  projectName: string;
  area: string;
  projectHolder: string;
  allocationDate: string;
  siteSurveyStart: string;
  siteSurveyEnd: string;
  contract: string;
  headCountStart: string;
  headCountEnd: string;
  proposalStart: string;
  proposalEnd: string;
  threedStart: string;
  threedEnd: string;
  tenderArchStart: string;
  tenderArchEnd: string;
  tenderMepStart: string;
  tenderMepEnd: string;
  boqStart: string;
  boqEnd: string;
  tenderStatus: string;
  comparative: string;
  workingDrawings: string;
  siteVisit: string;
  finalBill: string;
  projectClosure: string;
}

export const askariBankProjects: ProjectRow[] = [
    { id: 1, srNo: '1', projectName: 'AKBL AWT SADDAR RWP', area: '14,000', projectHolder: 'Noman Asad Mohsin', allocationDate: '6-Oct-25', siteSurveyStart: 'Done', siteSurveyEnd: '', contract: 'Received', headCountStart: '14-Oct-25', headCountEnd: '17-Oct-25', proposalStart: '17-Oct-25', proposalEnd: '21-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'sent', boqEnd: '', tenderStatus: 'sent', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 2, srNo: '2', projectName: 'AKBL CHAKLALA GARRISON RWP', area: '4,831', projectHolder: 'Noman Asad Mohsin', allocationDate: '13-Sep-25', siteSurveyStart: 'Received', siteSurveyEnd: 'In-Progress', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '1-Oct-25', proposalEnd: '3-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 3, srNo: '3', projectName: 'AKBL Priority Lounge', area: '24,000.00', projectHolder: 'Noman Haseeb Mohsin', allocationDate: '28-Mar-25', siteSurveyStart: 'DONE', siteSurveyEnd: '', contract: 'Received', headCountStart: '21-Apr-25', headCountEnd: '28-Apr-25', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'sent', boqEnd: '', tenderStatus: 'sent', comparative: '', workingDrawings: 'sent', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 4, srNo: '4', projectName: 'AKBL Ocean Mall KHI', area: '430.00', projectHolder: 'Noman Asad Mohsin', allocationDate: '10-Oct-25', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
];

export const hblProjects: ProjectRow[] = [
    { id: 101, srNo: '1', projectName: 'HBL PRESTIGE JOHER TOWN', area: '10,000', projectHolder: 'Luqman', allocationDate: '19-Sep-25', siteSurveyStart: '4-Aug-25', siteSurveyEnd: '5-Aug-25', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '22-Sep-25', proposalEnd: '8-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '21-Oct-25', tenderArchEnd: '25-Oct-25', tenderMepStart: '25-Oct-25', tenderMepEnd: '3-Nov-25', boqStart: '3-Nov-25', boqEnd: '4-Nov-25', tenderStatus: 'Send', comparative: '4-Nov-25', workingDrawings: '30-Oct-25', siteVisit: '15-Nov-25', finalBill: '', projectClosure: '' },
    { id: 102, srNo: '2', projectName: '68-A HBL Prestige & RBC CITY HOUSING SIALKOT-II', area: '9,880', projectHolder: 'Jabar Luqman', allocationDate: '28-Sep-25', siteSurveyStart: '2-Oct-25', siteSurveyEnd: '3-Oct-25', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '5-Oct-25', proposalEnd: '15-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Hold', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 103, srNo: '3', projectName: 'HBL DHA GUJRANWALA', area: '4,028', projectHolder: 'Luqman', allocationDate: '6-Sep-25', siteSurveyStart: '4-Sep-25', siteSurveyEnd: '5-Sep-25', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '8-Sep-25', proposalEnd: '12-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Hold', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 104, srNo: '4', projectName: 'HBL CITY HOUSING SIALKOT', area: '10,135', projectHolder: 'Luqman', allocationDate: '11-Sep-25', siteSurveyStart: '26-Aug-25', siteSurveyEnd: '27-Aug-25', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '12-Sep-25', proposalEnd: '18-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 105, srNo: '5', projectName: 'HBL ASLAM MOR LAYYAH', area: '2,022', projectHolder: 'MUJAHID Luqman', allocationDate: '11-Sep-25', siteSurveyStart: '21-Sep-25', siteSurveyEnd: '22-Sep-25', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '5-Oct-25', proposalEnd: '6-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '5-Oct-25', tenderArchEnd: '9-Oct-25', tenderMepStart: '9-Oct-25', tenderMepEnd: '12-Oct-25', boqStart: '12-Oct-25', boqEnd: '12-Oct-25', tenderStatus: 'Send', comparative: '', workingDrawings: '28-Oct-26', siteVisit: '4-Nov-25', finalBill: '1s visit', projectClosure: '' },
    { id: 106, srNo: '6', projectName: 'HBL Hellan Branch 1376 Gujranwala', area: '2,260', projectHolder: 'MUJAHID Luqman', allocationDate: '19-Sep-25', siteSurveyStart: '7-Sep-25', siteSurveyEnd: '8-Sep-25', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '5-Oct-25', proposalEnd: '27-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '28-Oct-25', tenderArchEnd: '3-Nov-25', tenderMepStart: '30-Oct-25', tenderMepEnd: '4-Nov-25', boqStart: '4-Nov-25', boqEnd: '5-Nov-25', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 107, srNo: '7', projectName: 'HBL Jaranwala Road', area: '2,725.00', projectHolder: 'Luqman Mujahid', allocationDate: '23-Aug-26', siteSurveyStart: '21-Aug-26', siteSurveyEnd: '21-Aug-26', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '21-Oct-25', proposalEnd: '25-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '14-Nov-25', siteVisit: '18-Nov-25', finalBill: '', projectClosure: '' },
    { id: 108, srNo: '8', projectName: 'HBL Poona branch', area: '1,422.00', projectHolder: 'Mujahid', allocationDate: 'N/A', siteSurveyStart: 'N/A', siteSurveyEnd: 'N/A', contract: 'Done', headCountStart: '', headCountEnd: '', proposalStart: '27-May-25', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '25-Oct-26', tenderArchEnd: '26-Oct-25', tenderMepStart: '27-Oct-26', tenderMepEnd: '1-Nov-25', boqStart: '26-Oct-25', boqEnd: '26-Oct-26', tenderStatus: 'Send', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 109, srNo: '9', projectName: 'HBL Raya Branch Lahore', area: '11,720.00', projectHolder: 'Luqman Adnan', allocationDate: '13-Dec-23', siteSurveyStart: '14-Dec-23', siteSurveyEnd: '16-Dec-23', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '13-Feb-24', proposalEnd: '27-Feb-24', threedStart: '28-Feb-24', threedEnd: '9-Mar-24', tenderArchStart: '11-Mar-24', tenderArchEnd: '26-Mar-24', tenderMepStart: '12-Mar-24', tenderMepEnd: '20-Mar-24', boqStart: '22-Mar-24', boqEnd: '30-Mar-24', tenderStatus: 'Send', comparative: 'Done', workingDrawings: '12-Mar-25', siteVisit: '20-Mar-25', finalBill: 'VISITS DONE', projectClosure: '' },
    { id: 110, srNo: '10', projectName: 'HBL Chowk Azam Branch 0847 Multan', area: '2,510.00', projectHolder: 'Luqman Mujahid', allocationDate: '9-Apr-26', siteSurveyStart: '17-Apr-26', siteSurveyEnd: '18-Apr-26', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '10-Jun-25', tenderArchEnd: '11-Jul-25', tenderMepStart: '23-Jun-25', tenderMepEnd: '30-Jun-26', boqStart: '11-Jul-25', boqEnd: '14-Jul-26', tenderStatus: 'Sent', comparative: '', workingDrawings: '16-Jul-25', siteVisit: '19-Jul-25', finalBill: '1s visit', projectClosure: '' },
    { id: 111, srNo: '11', projectName: 'HBL Islamic prestige', area: '1,778.00', projectHolder: 'Mohsin Ali', allocationDate: '26-Jul-25', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '28-Aug-25', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '1-Sep-25', boqEnd: '2-Sep-26', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const ublProjects: ProjectRow[] = [
    { id: 201, srNo: '1', projectName: 'UBL Bhowana, Chiniot', area: '7,600.00', projectHolder: 'Adnan Luqman', allocationDate: '06-May-25', siteSurveyStart: '20-May-25', siteSurveyEnd: '21-May-25', contract: 'Done', headCountStart: '06-May-25', headCountEnd: '', proposalStart: '06-Jul-25', proposalEnd: 'Done', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 202, srNo: '2', projectName: 'UBL QASIMABAD, HYDERABAD', area: '13,600.00', projectHolder: 'Done', allocationDate: 'Done', siteSurveyStart: 'Done', siteSurveyEnd: 'Done', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: 'Done', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: 'Done', boqEnd: 'Done', tenderStatus: 'Done', comparative: 'Done', workingDrawings: 'Done', siteVisit: 'Done', finalBill: '', projectClosure: '' },
    { id: 203, srNo: '3', projectName: 'UBL NELA-GUMBAD LHR', area: '', projectHolder: '', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Hold', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 204, srNo: '4', projectName: 'UBL PHASE 6', area: '13,085.00', projectHolder: 'Adnan Haseeb', allocationDate: '06-Apr-24', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: 'Sent', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: 'Pending', boqStart: '', boqEnd: 'Pending', tenderStatus: 'Done', comparative: 'In Revision', workingDrawings: 'In Revision', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 205, srNo: '5', projectName: 'State Life Society', area: '6,691.00', projectHolder: 'Adnan Haseeb', allocationDate: '06-Mar-24', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '23-Oct-24', siteVisit: '28-Oct-24', finalBill: '', projectClosure: '' }
];

export const mcbProjects: ProjectRow[] = [
    { id: 301, srNo: '1', projectName: 'MCB Emporium Branch Lahore', area: '3,200.00', projectHolder: 'Haseeb/ Adnan', allocationDate: '1-Dec-24', siteSurveyStart: '', siteSurveyEnd: '', contract: 'General Contract done', headCountStart: 'Recevied', headCountEnd: '', proposalStart: '1-Dec-24', proposalEnd: '24-Dec-24', threedStart: '23-Dec-24', threedEnd: '10-Jan-25', tenderArchStart: '6-Dec-24', tenderArchEnd: '18-Dec-24', tenderMepStart: '7-Apr-25', tenderMepEnd: '18-Apr-25', boqStart: '20-Apr-25', boqEnd: '23-Apr-25', tenderStatus: 'Sent', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 302, srNo: '2', projectName: 'MCB Islamic Dolmen Mall', area: '802.00', projectHolder: 'Haseeb', allocationDate: '27-Jan-25', siteSurveyStart: '', siteSurveyEnd: '', contract: 'General Contract done', headCountStart: 'Recevled', headCountEnd: '', proposalStart: '27-Jan-25', proposalEnd: '18-Feb-25', threedStart: '24-Feb-25', threedEnd: '3-Mar-25', tenderArchStart: '3-Mar-25', tenderArchEnd: '10-Mar-25', tenderMepStart: '25-Apr-25', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 303, srNo: '3', projectName: 'MCB Islamic Gulberg', area: '72,270.00', projectHolder: 'Jabbar/ Asad Shah', allocationDate: '15-Apr-25', siteSurveyStart: '22-Aug-25', siteSurveyEnd: '23-Aug-25', contract: 'Done', headCountStart: 'Recevied', headCountEnd: '', proposalStart: '15-Apr-25', proposalEnd: '30-Aug-25', threedStart: '15-Apr-25', threedEnd: '30-Aug-25', tenderArchStart: '13-Sep-25', tenderArchEnd: '', tenderMepStart: '4-Oct-25', tenderMepEnd: '8-Oct-25', boqStart: '', boqEnd: '', tenderStatus: 'Sent', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const fblProjects: ProjectRow[] = [
    { id: 401, srNo: '1', projectName: 'FBL-Finance Center-Gulberg LHR', area: '16500', projectHolder: 'Luqman', allocationDate: '23-Oct-25', siteSurveyStart: '24-Oct-25', siteSurveyEnd: '24-Oct-25', contract: '', headCountStart: 'Received', headCountEnd: '', proposalStart: '24-Oct-25', proposalEnd: '5-Nov-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 402, srNo: '2', projectName: 'FBL-Finance Center-F10 Islamabad', area: '10100', projectHolder: 'Luqman', allocationDate: '18-Oct-25', siteSurveyStart: '20-Oct-25', siteSurveyEnd: '20-Oct-25', contract: '', headCountStart: 'Received', headCountEnd: '', proposalStart: '27-Oct-25', proposalEnd: '8-Nov-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 403, srNo: '3', projectName: 'FBL JEHANGIRA NOWSHERA KPK', area: '2740', projectHolder: 'Luqman', allocationDate: '16-Oct-25', siteSurveyStart: '5-Oct-25', siteSurveyEnd: '6-Oct-25', contract: '', headCountStart: 'Received', headCountEnd: '', proposalStart: '16-Oct-25', proposalEnd: '18-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '20-Oct-25', tenderArchEnd: '25-Oct-25', tenderMepStart: '26-Oct-25', tenderMepEnd: '4-Nov-25', boqStart: '27-Oct-25', boqEnd: '27-Oct-25', tenderStatus: 'Sent', comparative: '', workingDrawings: '4-Nov-25', siteVisit: '8-Nov-25', finalBill: '', projectClosure: '' },
    { id: 404, srNo: '4', projectName: 'FBL IBB Chinar Road Mansehra KPK', area: '2612', projectHolder: 'Luqman', allocationDate: '24-Sep-25', siteSurveyStart: '30-Sep-25', siteSurveyEnd: '1-Oct-25', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '2-Oct-25', proposalEnd: '3-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '20-Oct-25', tenderArchEnd: '25-Oct-25', tenderMepStart: '30-Oct-25', tenderMepEnd: '4-Nov-25', boqStart: '27-Oct-25', boqEnd: '27-Oct-25', tenderStatus: 'Sent', comparative: '', workingDrawings: '8-Nov-25', siteVisit: '12-Nov-25', finalBill: '', projectClosure: '' },
    { id: 405, srNo: '5', projectName: 'FBL Jameel Chowk Peshawar', area: '2259', projectHolder: 'Luqman', allocationDate: '22-Sep-25', siteSurveyStart: '1-Oct-25', siteSurveyEnd: '2-Oct-25', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '2-Oct-25', proposalEnd: '4-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '20-Oct-25', tenderArchEnd: '25-Oct-25', tenderMepStart: '30-Oct-25', tenderMepEnd: '4-Nov-25', boqStart: '27-Oct-25', boqEnd: '27-Oct-25', tenderStatus: 'Sent', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 406, srNo: '6', projectName: 'FBL Jhangi Branch Gujranwala', area: '2270', projectHolder: 'Luqman Mujahid', allocationDate: '8-Sep-25', siteSurveyStart: '4-Sep-25', siteSurveyEnd: '5-Sep-25', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '8-Sep-25', proposalEnd: '11-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '15-Sep-25', tenderArchEnd: '24-Sep-25', tenderMepStart: '10-Oct-25', tenderMepEnd: '12-Oct-25', boqStart: '2-Oct-25', boqEnd: '4-Oct-25', tenderStatus: 'Sent', comparative: 'Done', workingDrawings: '21-Oct-25', siteVisit: '25-Oct-25', finalBill: '', projectClosure: '' },
    { id: 407, srNo: '7', projectName: 'FBL Ferozpur Road Lahore', area: '2492', projectHolder: 'Luqman Mujahid', allocationDate: '8-Sep-25', siteSurveyStart: '5-Sep-25', siteSurveyEnd: '6-Sep-25', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '8-Sep-25', proposalEnd: '12-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '13-Sep-25', tenderArchEnd: '24-Sep-25', tenderMepStart: '10-Oct-25', tenderMepEnd: '14-Oct-25', boqStart: '2-Oct-25', boqEnd: '4-Oct-25', tenderStatus: 'Sent', comparative: '', workingDrawings: '2-Nov-25', siteVisit: '5-Nov-25', finalBill: '', projectClosure: '' },
    { id: 408, srNo: '8', projectName: 'FBL Park View City Lahore', area: '2,900.00', projectHolder: 'Luqman Mujahid', allocationDate: '5-Sep-25', siteSurveyStart: '3-Sep-25', siteSurveyEnd: '4-Sep-25', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '5-Sep-25', proposalEnd: '12-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '15-Sep-25', tenderArchEnd: '24-Sep-25', tenderMepStart: '2-Oct-25', tenderMepEnd: '4-Oct-25', boqStart: '25-Sep-25', boqEnd: '27-Sep-25', tenderStatus: 'Sent', comparative: '', workingDrawings: '6-Nov-25', siteVisit: '9-Nov-25', finalBill: '', projectClosure: '' },
    { id: 409, srNo: '9', projectName: 'FBL CPC-KHARIAN-BRANCH', area: '1,635.00', projectHolder: 'Luqman Mujahid', allocationDate: '20-Aug-25', siteSurveyStart: '21-Aug-25', siteSurveyEnd: '22-Aug-25', contract: '', headCountStart: 'Received', headCountEnd: '', proposalStart: '5-Sep-25', proposalEnd: '11-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 410, srNo: '10', projectName: 'FBL Bhowana.', area: '2,183.00', projectHolder: 'Luqman Mujahid', allocationDate: '', siteSurveyStart: '16-Jul-25', siteSurveyEnd: '17-Jul-25', contract: '', headCountStart: 'Received', headCountEnd: '', proposalStart: '9-Aug-25', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '25-Aug-25', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'sent', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 411, srNo: '11', projectName: 'FBL Peer-Wadahi Road Branch Rawalpindi', area: '2,098.00', projectHolder: 'Noman', allocationDate: '23-Apr-25', siteSurveyStart: '24-Apr-25', siteSurveyEnd: '25-Apr-25', contract: 'N/A', headCountStart: 'N/A', headCountEnd: '', proposalStart: 'N/A', proposalEnd: 'N/A', threedStart: 'N/A', threedEnd: 'N/A', tenderArchStart: 'N/A', tenderArchEnd: 'N/A', tenderMepStart: 'N/A', tenderMepEnd: 'N/A', boqStart: 'N/A', boqEnd: 'N/A', tenderStatus: 'sent', comparative: '', workingDrawings: '', siteVisit: 'DONE', finalBill: '', projectClosure: '' },
    { id: 412, srNo: '12', projectName: 'FBL Gulbahar, Peshawer', area: '2,000.00', projectHolder: 'Noman', allocationDate: '24-Oct-24', siteSurveyStart: '4-Nov-24', siteSurveyEnd: '5-Nov-24', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '8-Nov-24', proposalEnd: '12-Nov-24', threedStart: '13-Nov-24', threedEnd: '15-Nov-24', tenderArchStart: '16-Nov-24', tenderArchEnd: '24-Nov-24', tenderMepStart: '15-Nov-24', tenderMepEnd: '22-Nov-24', boqStart: '23-Nov-24', boqEnd: '26-Nov-24', tenderStatus: 'sent', comparative: 'Done', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 413, srNo: '13', projectName: 'FBL Guest House DHA Phase-4 Lahore', area: '4,500.00', projectHolder: 'Noman', allocationDate: '1-Aug-24', siteSurveyStart: '6-Aug-24', siteSurveyEnd: '7-Aug-24', contract: 'Done', headCountStart: 'N/A', headCountEnd: '', proposalStart: '22-Aug-24', proposalEnd: '16-Sep-24', threedStart: 'N/A', threedEnd: 'N/A', tenderArchStart: '1-Oct-24', tenderArchEnd: '26-Oct-24', tenderMepStart: '', tenderMepEnd: '', boqStart: '28-Feb-25', boqEnd: '1-Mar-25', tenderStatus: 'sent', comparative: 'Done', workingDrawings: '', siteVisit: '', finalBill: 'PENDING', projectClosure: '' },
    { id: 414, srNo: '14', projectName: 'FBL Shahdara', area: '2,678.00', projectHolder: 'Adnan', allocationDate: '11-Jun-25', siteSurveyStart: '11-Jun-25', siteSurveyEnd: '13-Jun-25', contract: 'Done', headCountStart: 'Received', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '16-Jun-25', tenderArchEnd: '21-Jun-25', tenderMepStart: '22-Jun-25', tenderMepEnd: '26-Jun-25', boqStart: 'sent', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 415, srNo: '15', projectName: 'FBL RHQ (LG + GF)', area: '33,102.00', projectHolder: 'Luqman Haseeb', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '28-Aug-25', threedEnd: '28-Aug-25', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'sent', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 416, srNo: '16', projectName: 'FBL RHQ (Basment)', area: '33,102.00', projectHolder: 'Luqman Haseeb', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: 'WAITING', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const dibProjects: ProjectRow[] = [
     { id: 501, srNo: '1', projectName: 'DUBAI ISLAMIC BANK LHR', area: '7,550.00', projectHolder: 'ASAD MUJAHID', allocationDate: '19-Sep-25', siteSurveyStart: '20-Sep-25', siteSurveyEnd: '20-Sep-25', contract: '', headCountStart: 'DONE', headCountEnd: '', proposalStart: '24-Sep-25', proposalEnd: '28-Sep-25', threedStart: '3-Oct-25', threedEnd: '3-Nov-25', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const bankAlfalahProjects: ProjectRow[] = [
    { id: 601, srNo: '1', projectName: 'BALF Currency Exchange Dolmen Mall Lahore', area: '800.00', projectHolder: 'Haseeb', allocationDate: '26-May-25', siteSurveyStart: '04-Apr-25', siteSurveyEnd: '04-Apr-25', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '05-Apr-25', proposalEnd: '11-Apr-25', threedStart: '14-Apr-25', threedEnd: '18-Apr-25', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '10-Sep-25', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Sent', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 602, srNo: '2', projectName: 'Bank Al-Falah Brand Manual', area: 'N/A', projectHolder: 'Zain', allocationDate: '02-Feb-25', siteSurveyStart: 'N/A', siteSurveyEnd: 'N/A', contract: '11-Feb-25', headCountStart: 'N/A', headCountEnd: 'N/A', proposalStart: 'N/A', proposalEnd: 'N/A', threedStart: 'N/A', threedEnd: 'N/A', tenderArchStart: 'N/A', tenderArchEnd: 'N/A', tenderMepStart: '05-Aug-25', tenderMepEnd: '', boqStart: 'N/A', boqEnd: 'N/A', tenderStatus: 'N/A', comparative: 'N/A', workingDrawings: 'N/A', siteVisit: 'N/A', finalBill: 'N/A', projectClosure: '' },
    { id: 603, srNo: '3', projectName: 'BALF Shahdin Manzil Branch Lahore', area: '3,830.00', projectHolder: 'Mujahid Luqman', allocationDate: 'N/A', siteSurveyStart: 'N/A', siteSurveyEnd: 'N/A', contract: 'Received', headCountStart: '', headCountEnd: '', proposalStart: '25-Sep-25', proposalEnd: '21-Oct-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const bankAlHabibProjects: ProjectRow[] = [
    { id: 701, srNo: '1', projectName: 'Bank Al Habib CLIFTON BRANCH', area: '5,500.00', projectHolder: '', allocationDate: '13-Oct-25', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: 'DONE', headCountEnd: '', proposalStart: '14-Oct-25', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 702, srNo: '2', projectName: 'Khyaban-e-Hafiz Office and Branch', area: '13,500.00', projectHolder: '', allocationDate: '13-Oct-25', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: 'DONE', headCountEnd: '', proposalStart: '14-Oct-25', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const cbdProjects: ProjectRow[] = [
    { id: 801, srNo: '1', projectName: 'Nawaz sharif Business Hub', area: '25 Kanals', projectHolder: 'ASAD/WALEED/Jabbar', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 802, srNo: '2', projectName: 'C-B-D', area: '', projectHolder: 'ASAD/WALEED', allocationDate: '16-Jun-25', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '16-Jun-25', headCountEnd: '', proposalStart: '16-Jun-25', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const commercialProjects: ProjectRow[] = [
    { id: 901, srNo: '1', projectName: 'Enertech Hydo-China Thar Sindh (Office Building)', area: '5,000.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '3/28/2025', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'Furniture BOQ & Lights BOQ in Progress.', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 902, srNo: '2', projectName: 'Enertech Hydo-China Thar Sindh (Officer Bungalow)', area: '2,000.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '3/28/2026', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'Furniture BOQ & Lights BOQ in Progress.', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 903, srNo: '3', projectName: 'Enertech Hydo-China Thar Sindh (Guest House)', area: '6,500.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '3/28/2027', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'Furniture BOQ & Lights BOQ In Progress.', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 904, srNo: '4', projectName: 'Enertech Hydo-China Thar Sindh (Bachelor Accommodation)', area: '8,850.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '3/28/2028', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'Furniture BOQ & Lights BOQ In Progress.', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 905, srNo: '5', projectName: 'Bestway Tower', area: '', projectHolder: 'ASAD', allocationDate: 'N/A', siteSurveyStart: '', siteSurveyEnd: 'Done', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: 'Done', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: '', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawings: 'EXTERIOR 3D IN REVISION', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 906, srNo: '6', projectName: 'French Club', area: '', projectHolder: 'LUQMAN', allocationDate: 'N/A', siteSurveyStart: '', siteSurveyEnd: 'Done', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: '', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: '', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawings: 'All drawings sent', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 907, srNo: '7', projectName: 'DIN Tower', area: '', projectHolder: 'NOMAN WAQAS', allocationDate: 'N/A', siteSurveyStart: '', siteSurveyEnd: 'Done', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: '', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: '', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawings: 'Final payment RECEIVED', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 908, srNo: '8', projectName: 'Mr Nadeem Riaz Office Dolmen Mall', area: '', projectHolder: 'LUQMAN NOMAN', allocationDate: 'N/A', siteSurveyStart: '', siteSurveyEnd: 'Done', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: '', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'Everything has been sent. QUERIES ONLY', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 909, srNo: '9', projectName: 'Mr Brad Office Dolmen Mall', area: '', projectHolder: 'LUQMAN NOMAN', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: 'Done', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: '', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'All drawings sent', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 910, srNo: '10', projectName: 'BAMSOL', area: '22,332.00', projectHolder: 'Haseeb ASAD', allocationDate: '18-Aug-25', siteSurveyStart: 'AS BUILT', siteSurveyEnd: 'RECEIVED', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: '28-Aug-25', proposalEnd: '25-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'Proposal shared and minor revisions in proposal.', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 911, srNo: '11', projectName: 'Aghaz Housing', area: '', projectHolder: '', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: 'All drawings sent', siteVisit: '', finalBill: '', projectClosure: '' }
];

export const residentialProjects: ProjectRow[] = [
    { id: 1001, srNo: '1', projectName: 'Mr Asim Khan', area: '', projectHolder: '', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: '12-Oct-25', threedEnd: 'Done', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: 'Done', boqEnd: 'Done', tenderStatus: 'Done', comparative: 'Done', workingDrawings: 'Done', siteVisit: 'Done', finalBill: 'Done', projectClosure: 'Done' },
    { id: 1002, srNo: '2', projectName: 'Mr Waleed Mustaq', area: '', projectHolder: 'Khizar', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCountStart: 'Done', headCountEnd: '', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: 'Done', tenderArchStart: 'Done', tenderArchEnd: 'Done', tenderMepStart: 'Done', tenderMepEnd: 'Done', boqStart: 'Done', boqEnd: 'Done', tenderStatus: 'Done', comparative: 'Done', workingDrawings: 'Done', siteVisit: 'Done', finalBill: 'Done', projectClosure: 'Done' },
    { id: 1003, srNo: '3', projectName: 'Mr. Shahpar Masood', area: '', projectHolder: 'Sobia/Waqas', allocationDate: '23-Jul-25', siteSurveyStart: 'n/a', siteSurveyEnd: '', contract: 'Done', headCountStart: '', headCountEnd: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 1004, srNo: '4', projectName: 'Rana Sajjad', area: '', projectHolder: 'Sobia/Amna', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCountStart: '', headCountEnd: '', proposalStart: '1-Jul-25', proposalEnd: '12-Aug-25', threedStart: '6-Aug-25', threedEnd: '23-Jul-25', tenderArchStart: '14-Sep-25', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawings: '', siteVisit: '', finalBill: '', projectClosure: '' },
];

export const allProjects: ProjectRow[] = [
    ...askariBankProjects,
    ...hblProjects,
    ...ublProjects,
    ...mcbProjects,
    ...fblProjects,
    ...dibProjects,
    ...bankAlfalahProjects,
    ...bankAlHabibProjects,
    ...cbdProjects,
    ...commercialProjects,
    ...residentialProjects
];

export const bankProjectsMap: Record<string, ProjectRow[]> = {
    "askari bank": askariBankProjects,
    "hbl": hblProjects,
    "ubl": ublProjects,
    "mcb": mcbProjects,
    "fbl": fblProjects,
    "dib": dibProjects,
    "bank alfalah": bankAlfalahProjects,
    "bank al habib": bankAlHabibProjects,
    "cbd": cbdProjects,
    "commercial": commercialProjects,
    "residential": residentialProjects,
};
