
export interface ProjectRow {
  id: number;
  srNo: string;
  projectName: string;
  area: string;
  projectHolder: string;
  allocationDate: string;
  siteSurveyStart: string;
  siteSurveyEnd: string;
  contract: string;
  headCount: string;
  proposalStart: string;
  proposalEnd: string;
  threedStart: string;
  threedEnd: string;
  tenderArchStart: string;
  tenderArchEnd: string;
  tenderMepStart: string;
  tenderMepEnd: string;
  boqStart: string;
  boqEnd: string;
  tenderStatus: string;
  comparative: string;
  workingDrawingsStart?: string;
  workingDrawingsEnd?: string;
  siteVisit?: string;
  finalBill: string;
  projectClosure: string;
  contractStart?: string;
  contactEnd?: string;
  headCountStart?: string;
  headCountEnd?: string;
}

export let askariBankProjects: ProjectRow[] = [
    { id: 1, srNo: '1', projectName: 'AKBL F6 MARKAZ', area: '14,000', projectHolder: 'Noman Asad', allocationDate: '5813', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'final drawings has been sent only animation need to amend and resend.', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 2, srNo: '2', projectName: 'AKBL AWT SADDAR RWP', area: '14,000', projectHolder: 'Noman Asad Mohsin', allocationDate: '2025-10-06', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: 'Received', proposalStart: '2025-10-14', proposalEnd: '2025-10-17', threedStart: '2025-10-17', threedEnd: '2025-10-21', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 3, srNo: '3', projectName: 'AKBL CHAKLALA GARRISON RWP', area: '4,831', projectHolder: 'Noman Asad Mohsin', allocationDate: '2025-09-13', siteSurveyStart: '', siteSurveyEnd: 'Recleved', contract: 'In-Progress', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '2025-10-01', threedEnd: '2025-10-03', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 4, srNo: '4', projectName: 'AKBL Priority Lounge', area: '24,000.00', projectHolder: 'Noman Haseeb Mohsin', allocationDate: '2025-03-28', siteSurveyStart: '', siteSurveyEnd: '', contract: 'DONE', headCount: 'Recevied', proposalStart: '2025-04-21', proposalEnd: '2025-04-28', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'sent', boqEnd: '', tenderStatus: 'sent', comparative: '', workingDrawingsStart: 'sent', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 5, srNo: '5', projectName: 'AKBL Ocean Mall KHI', area: '430.00', projectHolder: 'Noman Asad Mohsin', allocationDate: '2025-10-10', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export let hblProjects: ProjectRow[] = [
    { id: 101, srNo: '1', projectName: 'HBL JOHER TOWN RBC & PRESTIGE', area: '10,000', projectHolder: 'Luqman', allocationDate: '2025-09-19', siteSurveyStart: '2025-08-04', siteSurveyEnd: '2025-08-06', contract: '', headCount: 'Received', proposalStart: '2025-09-22', proposalEnd: '2025-10-08', threedStart: '', threedEnd: '', tenderArchStart: '2025-12-08', tenderArchEnd: '2025-12-19', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Tender Start', comparative: '', workingDrawingsStart: '2025-12-08', workingDrawingsEnd: '2025-12-19', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 102, srNo: '2', projectName: '68-A HBL Prestige & RBC CITY HOUSING SIALKOT -II', area: '9,880', projectHolder: 'Luqman Waqas', allocationDate: '2025-09-28', siteSurveyStart: '2025-10-02', siteSurveyEnd: '2025-10-03', contract: 'Done', headCount: 'Received', proposalStart: '2025-10-05', proposalEnd: '2025-10-15', threedStart: '2025-12-04', threedEnd: '2025-12-08', tenderArchStart: '2025-10-21', tenderArchEnd: '2025-10-25', tenderMepStart: '2025-10-25', tenderMepEnd: '2025-11-03', boqStart: '2025-11-03', boqEnd: '2025-11-04', tenderStatus: 'Today will shared', comparative: '2025-11-04', workingDrawingsStart: '2025-10-30', workingDrawingsEnd: '2025-12-08', siteVisit: '14-Nov-25', finalBill: '', projectClosure: '' },
    { id: 103, srNo: '3', projectName: 'HBL VALENCIA TOWN RBC & PRESTIGE', area: '5,418', projectHolder: 'Luqman Waqas', allocationDate: '2025-09-06', siteSurveyStart: '2025-09-04', siteSurveyEnd: '2025-09-05', contract: '', headCount: 'Received', proposalStart: '2025-10-30', proposalEnd: '2025-12-08', threedStart: '', threedEnd: '', tenderArchStart: '2025-12-19', tenderArchEnd: '2025-12-29', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '2026-01-12', workingDrawingsEnd: '2026-01-23', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 104, srNo: '4', projectName: 'HBL EXPO CENTER RBC & PRESTIGE', area: '3,080', projectHolder: 'Luqman Waqas', allocationDate: '2025-11-05', siteSurveyStart: '2025-11-07', siteSurveyEnd: '2025-11-08', contract: '', headCount: 'Received', proposalStart: '2025-11-09', proposalEnd: '2025-11-15', threedStart: '', threedEnd: '', tenderArchStart: '2025-12-28', tenderArchEnd: '2026-01-12', tenderMepStart: '2025-10-25', tenderMepEnd: '2025-11-03', boqStart: '2025-11-03', boqEnd: '2025-11-04', tenderStatus: '', comparative: '2025-11-04', workingDrawingsStart: '2025-12-28', workingDrawingsEnd: '2026-01-12', siteVisit: '14-Nov-25', finalBill: '', projectClosure: '' },
    { id: 105, srNo: '5', projectName: 'HBL DEPALPUR PAKPATAN ROAD', area: '6,552', projectHolder: 'Luqman Waqas', allocationDate: '2025-12-11', siteSurveyStart: '2025-09-16', siteSurveyEnd: '2025-09-17', contract: '', headCount: 'Received', proposalStart: '2025-12-12', proposalEnd: '2025-12-15', threedStart: '', threedEnd: '', tenderArchStart: '2025-12-16', tenderArchEnd: '2025-12-26', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 106, srNo: '6', projectName: 'HBL Chowk Azam Branch 0847 Multan', area: '2,022', projectHolder: 'MUJAHID Luqman', allocationDate: '2025-09-11', siteSurveyStart: '2025-09-21', siteSurveyEnd: '2025-09-22', contract: 'Done', headCount: 'Received', proposalStart: '2025-10-05', proposalEnd: '2025-10-06', threedStart: '', threedEnd: '', tenderArchStart: '2025-10-05', tenderArchEnd: '2025-10-09', tenderMepStart: '2025-10-09', tenderMepEnd: '2025-10-12', boqStart: '2025-10-12', boqEnd: '2025-10-12', tenderStatus: 'Send', comparative: '', workingDrawingsStart: '2025-10-28', workingDrawingsEnd: '2025-11-04', siteVisit: '07-Oct-25', finalBill: '', projectClosure: '' },
    { id: 107, srNo: '7', projectName: 'HBL Hellan Branch 1375 Gujranwala', area: '2,260', projectHolder: 'MUJAHID Luqman', allocationDate: '2025-09-19', siteSurveyStart: '2025-09-07', siteSurveyEnd: '2025-09-08', contract: 'Done', headCount: 'Received', proposalStart: '2025-10-05', proposalEnd: '2025-10-27', threedStart: '', threedEnd: '', tenderArchStart: '2025-10-28', tenderArchEnd: '2025-11-03', tenderMepStart: '2025-10-30', tenderMepEnd: '2025-11-04', boqStart: '2025-11-04', boqEnd: '2025-11-05', tenderStatus: 'Tender Shared', comparative: '', workingDrawingsStart: '2025-11-14', workingDrawingsEnd: '2025-11-25', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 108, srNo: '8', projectName: 'HBL Jaranwala Road', area: '2,725.00', projectHolder: 'Luqman Mujahid', allocationDate: '2025-08-23', siteSurveyStart: '2025-08-21', siteSurveyEnd: '2025-08-21', contract: 'Done', headCount: 'Received', proposalStart: '2025-10-21', proposalEnd: '2025-10-25', threedStart: '', threedEnd: '', tenderArchStart: '2025-10-25', tenderArchEnd: '2025-10-26', tenderMepStart: '2025-10-27', tenderMepEnd: '2025-11-01', boqStart: '2025-10-26', boqEnd: '2025-10-26', tenderStatus: 'Construction Started', comparative: '', workingDrawingsStart: '2025-11-14', workingDrawingsEnd: '2025-11-18', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 109, srNo: '9', projectName: 'HBL Poona branch', area: '1,422.00', projectHolder: 'Mujahid', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCount: '', proposalStart: '2025-05-27', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '2025-08-04', tenderMepEnd: '2025-08-08', boqStart: '', boqEnd: '', tenderStatus: 'Layout Revise', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '2025-10-07', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 110, srNo: '10', projectName: 'HBL Chowk Azam Branch 0847 Multan', area: '2,510.00', projectHolder: 'Mujahid', allocationDate: '2025-04-09', siteSurveyStart: '2025-04-17', siteSurveyEnd: '2025-04-18', contract: 'Done', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '2025-06-10', tenderArchEnd: '2025-07-11', tenderMepStart: '2025-06-23', tenderMepEnd: '2025-06-30', boqStart: '2025-07-11', boqEnd: '2025-07-14', tenderStatus: 'Complete', comparative: '', workingDrawingsStart: '2025-07-16', workingDrawingsEnd: '2025-07-19', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 111, srNo: '11', projectName: 'HBL Islamic prestige Brand Manual', area: '1,778.00', projectHolder: 'Mohsin Ali', allocationDate: '2025-07-25', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '2025-08-28', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '2025-09-01', boqEnd: '2025-09-02', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export let ublProjects: ProjectRow[] = [
    { id: 201, srNo: '1', projectName: 'UBL Bhowana, Chiniot', area: '7,600.00', projectHolder: 'Adnan Luqman', allocationDate: '2025-05-06', siteSurveyStart: '2025-05-20', siteSurveyEnd: '2025-05-21', contract: 'Done', headCount: '2025-05-06', proposalStart: '2025-07-06', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'on Hold', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 202, srNo: '2', projectName: 'UBL QASIMABAD, HYDERABAD', area: '13,600.00', projectHolder: '', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Construction in Progress.', comparative: 'Done', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 203, srNo: '3', projectName: 'UBL-Small Medium Enterprises', area: '6,275.00', projectHolder: 'Noman/Mujahid', allocationDate: '2025-09-05', siteSurveyStart: '2025-09-09', siteSurveyEnd: '2025-09-10', contract: 'Done', headCount: 'Done', proposalStart: '2025-09-18', proposalEnd: '2025-09-24', threedStart: '', threedEnd: '', tenderArchStart: '2025-10-14', tenderArchEnd: '2025-10-15', tenderMepStart: '', tenderMepEnd: '', boqStart: '2025-10-14', boqEnd: '2025-10-15', tenderStatus: 'Tender shared', comparative: '', workingDrawingsStart: '2025-10-21', workingDrawingsEnd: '2025-10-22', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 205, srNo: '4', projectName: 'UBL PHASE 6', area: '13,085.00', projectHolder: 'Adnan Haseeb', allocationDate: '2024-04-06', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: 'Sent', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Construction in Progress.', comparative: 'In Revision', workingDrawingsStart: '', workingDrawingsEnd: 'In Revision', siteVisit: '04-Dec-25', finalBill: '', projectClosure: '' },
    { id: 206, srNo: '5', projectName: 'UBL State Life Society', area: '6,691.00', projectHolder: 'Adnan Haseeb', allocationDate: '2024-03-06', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: '', proposalEnd: 'Done', threedStart: '', threedEnd: '', tenderArchStart: 'Sent', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Construction in Progress.', comparative: '', workingDrawingsStart: '2024-10-23', workingDrawingsEnd: '2024-12-01', siteVisit: '04-Dec-25', finalBill: '', projectClosure: '' }
];

export let mcbProjects: ProjectRow[] = [
    { id: 301, srNo: '1', projectName: 'MCB Emporium Branch Lahore', area: '3,200.00', projectHolder: 'Haseeb/Waqas', allocationDate: '2024-12-01', siteSurveyStart: '', siteSurveyEnd: '', contract: 'General Contract done', headCount: 'Recevied', proposalStart: '2024-12-01', proposalEnd: '2024-12-24', threedStart: '2024-12-23', threedEnd: '2025-01-10', tenderArchStart: '2024-12-06', tenderArchEnd: '2024-12-18', tenderMepStart: '2025-04-07', tenderMepEnd: '2025-04-18', boqStart: '2025-04-20', boqEnd: '2025-04-23', tenderStatus: 'Tender Working as per new theme.', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 302, srNo: '2', projectName: 'MCB Islamic Gulberg', area: '72,270.00', projectHolder: 'Jabbar/Asad Shah', allocationDate: '2025-04-15', siteSurveyStart: '2025-08-22', siteSurveyEnd: '2025-08-23', contract: 'Done', headCount: 'Recevied', proposalStart: '2025-04-15', proposalEnd: '2025-08-30', threedStart: '2025-04-15', threedEnd: '2025-08-30', tenderArchStart: '2025-09-13', tenderArchEnd: '', tenderMepStart: '2025-10-04', tenderMepEnd: '2025-10-08', boqStart: '', boqEnd: '', tenderStatus: 'Proposal sent and waiting for approval.', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export let fblProjects: ProjectRow[] = [
    { id: 401, srNo: '1', projectName: 'FBL-Finance Center-Gulberg LHR', area: '16500', projectHolder: 'Luqman', allocationDate: '2025-10-23', siteSurveyStart: '2025-10-24', siteSurveyEnd: '2025-10-24', contract: '', headCount: 'Received', proposalStart: '2025-10-24', proposalEnd: '2025-11-12', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Revised Layout shared', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 402, srNo: '2', projectName: 'FBL-Finance Center-F10 Islamabad', area: '10100', projectHolder: 'Luqman', allocationDate: '2025-10-18', siteSurveyStart: '2025-10-20', siteSurveyEnd: '2025-10-20', contract: '', headCount: 'Received', proposalStart: '2025-10-27', proposalEnd: '2025-11-08', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Revised Layout shared', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 403, srNo: '3', projectName: 'FBL PECO ROAD LAHORE', area: '3100', projectHolder: 'Luqman WAQAS', allocationDate: '2025-11-23', siteSurveyStart: '2025-11-25', siteSurveyEnd: '2025-11-26', contract: '', headCount: 'Received', proposalStart: '2025-11-28', proposalEnd: '2025-12-01', threedStart: '', threedEnd: '', tenderArchStart: '2025-12-02', tenderArchEnd: '2025-12-06', tenderMepStart: '2025-12-06', tenderMepEnd: '2025-12-08', boqStart: '2025-12-08', boqEnd: '2025-12-09', tenderStatus: 'Tender Start', comparative: '', workingDrawingsStart: '2025-12-10', workingDrawingsEnd: '2025-12-14', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 404, srNo: '4', projectName: 'FBL JEHANGIRA NOWSHERA KPK', area: '2740', projectHolder: 'Luqman', allocationDate: '2025-10-16', siteSurveyStart: '2025-10-05', siteSurveyEnd: '2025-10-06', contract: 'Done', headCount: 'Received', proposalStart: '2025-10-16', proposalEnd: '2025-10-18', threedStart: '', threedEnd: '', tenderArchStart: '2025-10-20', tenderArchEnd: '2025-10-25', tenderMepStart: '2025-10-30', tenderMepEnd: '2025-11-04', boqStart: '2025-10-27', boqEnd: '2025-10-27', tenderStatus: 'Sent', comparative: 'Done', workingDrawingsStart: '2025-11-08', workingDrawingsEnd: '2025-11-12', siteVisit: '03-Dec-25', finalBill: '', projectClosure: '' },
    { id: 405, srNo: '5', projectName: 'FBL IBB Chinar Road Mansehra KPK', area: '2612', projectHolder: 'Luqman', allocationDate: '2025-09-24', siteSurveyStart: '2025-09-30', siteSurveyEnd: '2025-10-01', contract: 'Done', headCount: 'Received', proposalStart: '2025-10-02', proposalEnd: '2025-10-03', threedStart: '', threedEnd: '', tenderArchStart: '2025-10-20', tenderArchEnd: '2025-10-25', tenderMepStart: '2025-10-30', tenderMepEnd: '2025-11-04', boqStart: '2025-10-27', boqEnd: '2025-10-27', tenderStatus: 'Sent', comparative: 'Done', workingDrawingsStart: '2025-11-08', workingDrawingsEnd: '2025-11-12', siteVisit: '04-Dec-25', finalBill: '', projectClosure: '' },
    { id: 406, srNo: '6', projectName: 'FBL Jameel Chowk Peshawar', area: '2259', projectHolder: 'Luqman', allocationDate: '2025-09-22', siteSurveyStart: '2025-10-01', siteSurveyEnd: '2025-10-02', contract: 'Done', headCount: 'Received', proposalStart: '2025-10-02', proposalEnd: '2025-10-04', threedStart: '', threedEnd: '', tenderArchStart: '2025-10-20', tenderArchEnd: '2025-10-25', tenderMepStart: '2025-10-30', tenderMepEnd: '2025-11-04', boqStart: '2025-10-27', boqEnd: '2025-10-27', tenderStatus: 'Sent', comparative: 'Done', workingDrawingsStart: '2025-12-02', workingDrawingsEnd: '2025-12-13', siteVisit: '02-Dec-25', finalBill: '', projectClosure: '' },
    { id: 407, srNo: '7', projectName: 'FBL Jhangi Branch Gujranwala', area: '2270', projectHolder: 'Luqman Mujahid', allocationDate: '2025-09-08', siteSurveyStart: '2025-09-04', siteSurveyEnd: '2025-09-05', contract: 'Done', headCount: 'Received', proposalStart: '2025-09-08', proposalEnd: '2025-09-11', threedStart: '', threedEnd: '', tenderArchStart: '2025-09-15', tenderArchEnd: '2025-09-24', tenderMepStart: '2025-10-10', tenderMepEnd: '2025-10-14', boqStart: '2025-10-02', boqEnd: '2025-10-04', tenderStatus: 'Sent', comparative: 'Done', workingDrawingsStart: '2025-10-21', workingDrawingsEnd: '2025-10-25', siteVisit: '10-Dec-25', finalBill: '', projectClosure: '' },
    { id: 408, srNo: '8', projectName: 'FBL Ferozpur Road Lahore', area: '2492', projectHolder: 'Luqman Mujahid', allocationDate: '2025-09-08', siteSurveyStart: '2025-09-05', siteSurveyEnd: '2025-09-06', contract: 'Done', headCount: 'Received', proposalStart: '2025-09-08', proposalEnd: '2025-09-12', threedStart: '', threedEnd: '', tenderArchStart: '2025-09-13', tenderArchEnd: '2025-09-24', tenderMepStart: '2025-10-10', tenderMepEnd: '2025-10-14', boqStart: '2025-10-02', boqEnd: '2025-10-04', tenderStatus: 'Hold', comparative: '', workingDrawingsStart: '2025-11-02', workingDrawingsEnd: '2025-11-05', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 409, srNo: '9', projectName: 'FBL Park View City Lahore', area: '2,900.00', projectHolder: 'Luqman Mujahid', allocationDate: '2025-09-05', siteSurveyStart: '2025-09-03', siteSurveyEnd: '2025-09-04', contract: 'Done', headCount: 'Received', proposalStart: '2025-09-05', proposalEnd: '2025-09-12', threedStart: '', threedEnd: '', tenderArchStart: '2025-09-15', tenderArchEnd: '2025-09-24', tenderMepStart: '2025-10-02', tenderMepEnd: '2025-10-04', boqStart: '2025-09-25', boqEnd: '2025-09-27', tenderStatus: 'Sent', comparative: 'Done', workingDrawingsStart: '2025-11-06', workingDrawingsEnd: '2025-11-09', siteVisit: '09-Dec-25', finalBill: '', projectClosure: '' },
    { id: 410, srNo: '10', projectName: 'FBL CPC-KHARIAN-BRANCH', area: '1,635.00', projectHolder: 'Luqman Mujahid', allocationDate: '2025-08-20', siteSurveyStart: '2025-08-21', siteSurveyEnd: '2025-08-22', contract: '', headCount: 'Received', proposalStart: '2025-09-05', proposalEnd: '2025-09-11', threedStart: '', threedEnd: '', tenderArchStart: '2025-11-08', tenderArchEnd: '2025-11-12', tenderMepStart: '2025-11-13', tenderMepEnd: '2025-11-15', boqStart: '2025-11-13', boqEnd: '2025-11-15', tenderStatus: 'Sent', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 411, srNo: '11', projectName: 'FBL Bhowana.', area: '2,183.00', projectHolder: 'Luqman Mujahid', allocationDate: '', siteSurveyStart: '2025-07-16', siteSurveyEnd: '2025-07-17', contract: '', headCount: 'Received', proposalStart: '2025-08-09', proposalEnd: '', threedStart: '2025-08-25', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Construction Comp.', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '2025-12-13', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 412, srNo: '12', projectName: 'FBL Peer-Wadahi Road Branch Rawalpindi', area: '2,098.00', projectHolder: 'Noman', allocationDate: '2025-04-23', siteSurveyStart: '2025-04-24', siteSurveyEnd: '2025-04-25', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'sent', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: 'DONE', finalBill: '', projectClosure: '' },
    { id: 413, srNo: '13', projectName: 'FBL Gulbahar, Peshawer', area: '2,000.00', projectHolder: 'Noman', allocationDate: '2024-10-24', siteSurveyStart: '2024-11-04', siteSurveyEnd: '2024-11-05', contract: 'Done', headCount: 'Received', proposalStart: '2024-11-08', proposalEnd: '2024-11-12', threedStart: '2024-11-13', threedEnd: '2024-11-15', tenderArchStart: '2024-11-16', tenderArchEnd: '2024-11-24', tenderMepStart: '2024-11-15', tenderMepEnd: '2024-11-22', boqStart: '2024-11-23', boqEnd: '2024-11-26', tenderStatus: 'sent', comparative: 'Done', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '04-Dec-25', finalBill: '', projectClosure: '' },
    { id: 414, srNo: '14', projectName: 'FBL Guest House DHA Phase-4 Lahore', area: '4,500.00', projectHolder: 'Noman', allocationDate: '2024-08-01', siteSurveyStart: '2024-08-06', siteSurveyEnd: '2024-08-07', contract: 'Done', headCount: '', proposalStart: '2024-08-22', proposalEnd: '2024-09-16', threedStart: '', threedEnd: '', tenderArchStart: '2024-10-01', tenderArchEnd: '2024-10-26', tenderMepStart: '', tenderMepEnd: '', boqStart: '2025-02-28', boqEnd: '2025-03-01', tenderStatus: 'sent', comparative: 'Done', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: 'PENDING', finalBill: '', projectClosure: '' },
    { id: 415, srNo: '15', projectName: 'FBL Shahdara', area: '2,678.00', projectHolder: 'Adnan', allocationDate: '2025-06-11', siteSurveyStart: '2025-06-11', siteSurveyEnd: '2025-06-13', contract: 'Done', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '2025-06-16', tenderMepEnd: '2025-06-21', boqStart: '2025-06-22', boqEnd: '2025-06-26', tenderStatus: 'Construction Comp.', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: 'PENDING', finalBill: '', projectClosure: '' },
    { id: 416, srNo: '16', projectName: 'FBL RHQ (LG + GF)', area: '33,102.00', projectHolder: 'Luqman Haseeb', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '2025-08-28', threedEnd: '2025-08-28', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'sent', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: 'DONE', finalBill: '', projectClosure: '' },
    { id: 417, srNo: '17', projectName: 'FBL RHQ (Basment)', area: '33,102.00', projectHolder: 'Luqman Haseeb', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'WAITING', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: 'DONE', finalBill: '', projectClosure: '' }
];

export let dibProjects: ProjectRow[] = [
     { id: 501, srNo: '1', projectName: 'DUBAI ISLAMIC BANK LHR', area: '7,550.00', projectHolder: 'ASAD MUJAHID', allocationDate: '2025-09-19', siteSurveyStart: '2025-09-20', siteSurveyEnd: '2025-09-20', contract: 'Shared', headCount: 'DONE', proposalStart: '2025-09-24', proposalEnd: '2025-09-28', threedStart: '2025-10-03', threedEnd: '2025-11-03', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'PROPOSAL STAGE - No response from Bank.', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: 'Done', finalBill: '', projectClosure: '' }
];

export let bankAlfalahProjects: ProjectRow[] = [
    { id: 601, srNo: '1', projectName: 'BALF Currency Exchange Dolmen Mall Lahore', area: '800', projectHolder: 'Haseeb', allocationDate: '2025-05-26', siteSurveyStart: '2025-04-04', siteSurveyEnd: '2025-04-04', contract: 'Received', headCount: '', proposalStart: '2025-04-05', proposalEnd: '2025-04-11', threedStart: '2025-04-14', threedEnd: '2025-04-18', tenderArchStart: 'Sent', tenderArchEnd: '', tenderMepStart: '2025-09-10', tenderMepEnd: '', boqStart: 'Sent', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 602, srNo: '2', projectName: 'Bank Al-Falah Brand Manual', area: '', projectHolder: 'Zain', allocationDate: '2025-02-02', siteSurveyStart: '', siteSurveyEnd: '', contract: '2025-02-11', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '2025-08-05', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 603, srNo: '3', projectName: 'BALF Shahdin Manzil Branch Lahore', area: '3,830', projectHolder: 'Mujahid Luqman', allocationDate: 'Received', siteSurveyStart: 'Received', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '2025-09-25', proposalEnd: '2025-10-21', threedStart: 'Done', threedEnd: '', tenderArchStart: 'In progress', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export let bankAlHabibProjects: ProjectRow[] = [
    { id: 701, srNo: '1', projectName: 'Bank Al Habib CLIFTON BRANCH', area: '5,500.00', projectHolder: '', allocationDate: '2025-10-13', headCount: 'DONE', proposalStart: '2025-10-14', siteSurveyStart: '', siteSurveyEnd: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'PROPOSAL STAGE - No response from Bank.', comparative: '', finalBill: '', projectClosure: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', contract: '' },
    { id: 702, srNo: '2', projectName: 'Khyaban-e-Hafiz Office and Branch', area: '13,500.00', projectHolder: '', allocationDate: '2025-10-13', headCount: 'DONE', proposalStart: '2025-10-14', siteSurveyStart: '', siteSurveyEnd: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'PROPOSAL STAGE - No response from Bank.', comparative: '', finalBill: '', projectClosure: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', contract: '' }
];

export let cbdProjects: ProjectRow[] = [
    { id: 801, srNo: '1', projectName: 'C-B-D', area: '', projectHolder: 'ASAD/WALEED', allocationDate: '2025-06-16', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '2025-06-16', proposalStart: '2025-06-16', proposalEnd: '', threedStart: '2025-06-16', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: 'Material Board in Progress', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' }
];

export let commercialProjects: ProjectRow[] = [
    { id: 901, srNo: '1', projectName: 'Enertech Hydo-China Thar Sindh (Office Building)', area: '5,000.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '2025-03-28', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'Furniture BOQ & Lights BOQ in Progress.', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 902, srNo: '2', projectName: 'Enertech Hydo-China Thar Sindh (Officer Bungalow)', area: '2,000.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '2026-03-28', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'Furniture BOQ & Lights BOQ in Progress.', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 903, srNo: '3', projectName: 'Enertech Hydo-China Thar Sindh (Guest House)', area: '6,500.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '2027-03-28', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'Furniture BOQ & Lights BOQ in Progress.', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 904, srNo: '4', projectName: 'Enertech Hydo-China Thar Sindh (Bachelor Accommodation)', area: '8,850.00', projectHolder: 'MOHSIN/NOMAN', allocationDate: '2028-03-28', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: 'Furniture BOQ & Lights BOQ in Progress.', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 905, srNo: '5', projectName: 'Bestway Tower', area: '', projectHolder: 'ASAD', allocationDate: 'N/A', siteSurveyStart: 'Done', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: '', tenderMepStart: 'Done', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 906, srNo: '6', projectName: 'French Club', area: '', projectHolder: 'LUQMAN', allocationDate: 'N/A', siteSurveyStart: 'Done', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: '', tenderMepStart: 'Done', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 907, srNo: '7', projectName: 'DIN Tower', area: '', projectHolder: 'NOMAN WAQAS', allocationDate: 'N/A', siteSurveyStart: 'Done', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: '', tenderMepStart: 'Done', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 908, srNo: '8', projectName: 'Mr Nadeem Riaz Office Dolmen Mall', area: '', projectHolder: 'LUQMAN NOMAN', allocationDate: 'N/A', siteSurveyStart: 'Done', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: '', tenderMepStart: 'Done', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 909, srNo: '9', projectName: 'Mr Brad Office Dolmen Mall', area: '', projectHolder: 'LUQMAN NOMAN', allocationDate: 'N/A', siteSurveyStart: 'Done', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: '', tenderMepStart: 'Done', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Send', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 910, srNo: '10', projectName: 'BAMSOL', area: '22,332.00', projectHolder: 'Haseeb ASAD', allocationDate: '18-Aug-25', siteSurveyStart: 'AS BUILT RECEIVED', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: '28-Aug-25', proposalEnd: '25-Sep-25', threedStart: '', threedEnd: '', tenderArchStart: '25-Nov-25', tenderArchEnd: '18-Dec-25', tenderMepStart: '18-Dec-25', tenderMepEnd: '', boqStart: '18-Dec-25', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 911, srNo: '11', projectName: 'Aghaz Housing', area: '', projectHolder: '', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' }
];


export let residentialProjects: ProjectRow[] = [
    { id: 1001, srNo: '1', projectName: 'Mr Asim Khan', area: '', projectHolder: '', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: 'Done', threedStart: '2025-10-12', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: '', tenderMepStart: 'Done', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'final drawings has been sent only animation need to amend and resend.', comparative: 'Done', workingDrawingsStart: 'Done', workingDrawingsEnd: '', siteVisit: 'Done', finalBill: 'Done', projectClosure: 'Done' },
    { id: 1002, srNo: '2', projectName: 'Mr Waleed Mustaq', area: '', projectHolder: 'Khizar', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCount: 'Done', proposalStart: 'Done', proposalEnd: 'Done', threedStart: 'Done', threedEnd: '', tenderArchStart: 'Done', tenderArchEnd: '', tenderMepStart: 'Done', tenderMepEnd: '', boqStart: 'Done', boqEnd: '', tenderStatus: 'Done', comparative: 'Done', workingDrawingsStart: 'Done', workingDrawingsEnd: '', siteVisit: 'Done', finalBill: 'Done', projectClosure: 'Done' },
    { id: 1003, srNo: '3', projectName: 'Mr. Shahpar Masood', area: '', projectHolder: 'Sobia/Waqas', allocationDate: '2025-07-23', siteSurveyStart: '', siteSurveyEnd: '', contract: 'Done', headCount: '', proposalStart: '2025-07-01', proposalEnd: '2025-08-12', threedStart: '2025-08-06', threedEnd: '2025-07-23', tenderArchStart: '2025-10-10', tenderArchEnd: '2025-10-30', tenderMepStart: '2025-11-01', tenderMepEnd: '2025-11-05', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '2025-11-12', workingDrawingsEnd: '2025-12-18', siteVisit: '', finalBill: '', projectClosure: '' },
    { id: 1004, srNo: '4', projectName: 'Rana Sajjad', area: '', projectHolder: 'Sobia/Amna', allocationDate: '', siteSurveyStart: '', siteSurveyEnd: '', contract: '', headCount: '', proposalStart: '', proposalEnd: '', threedStart: '', threedEnd: '', tenderArchStart: '', tenderArchEnd: '', tenderMepStart: '', tenderMepEnd: '', boqStart: '', boqEnd: '', tenderStatus: '', comparative: '', workingDrawingsStart: '', workingDrawingsEnd: '', siteVisit: '', finalBill: '', projectClosure: '' },
];

export const allProjects: ProjectRow[] = [
    ...askariBankProjects,
    ...hblProjects,
    ...ublProjects,
    ...mcbProjects,
    ...fblProjects,
    ...dibProjects,
    ...bankAlfalahProjects,
    ...bankAlHabibProjects,
    ...cbdProjects,
    ...commercialProjects,
    ...residentialProjects
];

export const bankProjectsMap: Record<string, ProjectRow[]> = {
    "askari-bank": askariBankProjects,
    "hbl": hblProjects,
    "ubl": ublProjects,
    "mcb": mcbProjects,
    "faysal-bank": fblProjects,
    "dib": dibProjects,
    "bank-al-falah": bankAlfalahProjects,
    "bank-al-habib": bankAlHabibProjects,
    "cbd": cbdProjects,
    "commercial": commercialProjects,
    "residential": residentialProjects,
};

export const bankTimelineCategories = [
    "Askari Bank",
    "Bank Alfalah",
    "Bank Al Habib",
    "CBD",
    "DIB",
    "Faysal Bank",
    "HBL",
    "MCB",
    "UBL",
    "Commercial",
    "Residential"
];









